from __future__ import annotations

"""Level 1 permission definitions and default role mappings."""

PERMISSIONS = [
    # Profile (all staff + public user)
    ("profile.view", "View own profile", "profile"),
    ("profile.edit", "Edit own profile", "profile"),
    ("profile.change_password", "Change own password", "profile"),
    # Company
    ("company.view", "View company settings", "company"),
    ("company.edit", "Edit company settings", "company"),
    # User management
    ("users.view", "View staff users", "users"),
    ("users.create", "Create staff users", "users"),
    ("users.edit", "Edit staff users", "users"),
    ("users.reset_password", "Reset staff passwords", "users"),
    ("activity.view", "View activity logs", "users"),
    # Roles & permissions
    ("roles.view", "View role permission matrix", "roles"),
    # Reserved for upcoming Level 1 modules
    ("contacts.view", "View contacts", "contacts"),
    ("contacts.create", "Create contacts", "contacts"),
    ("contacts.edit", "Edit contacts", "contacts"),
    ("products.view", "View products", "products"),
    ("products.create", "Create products", "products"),
    ("products.edit", "Edit products", "products"),
    ("leads.view", "View leads", "leads"),
    ("leads.create", "Create leads", "leads"),
    ("leads.edit", "Edit leads", "leads"),
    ("leads.assign", "Assign leads to staff", "leads"),
    ("deals.view", "View sales pipeline", "deals"),
    ("deals.create", "Create deals", "deals"),
    ("deals.edit", "Edit deals and move stages", "deals"),
    ("deals.assign", "Assign deals to staff", "deals"),
    ("quotations.view", "View quotations", "quotations"),
    ("quotations.create", "Create quotations", "quotations"),
    ("quotations.edit_draft", "Edit draft quotations", "quotations"),
    ("quotations.submit_approval", "Submit quotations for approval", "quotations"),
    ("quotations.approve", "Approve quotations", "quotations"),
    ("quotations.send", "Send quotations to clients", "quotations"),
    ("quotations.cancel", "Cancel quotations", "quotations"),
    ("quotations.accept_override", "Override client acceptance/rejection", "quotations"),
    ("quotations.manage_templates", "Manage quotation templates and settings", "quotations"),
    ("sales_orders.view", "View sales orders", "sales_orders"),
    ("sales_orders.create", "Create sales orders", "sales_orders"),
    ("sales_orders.edit_draft", "Edit draft sales orders", "sales_orders"),
    ("sales_orders.convert_from_quote", "Convert quotations to sales orders", "sales_orders"),
    ("sales_orders.confirm", "Confirm sales orders", "sales_orders"),
    ("sales_orders.update_progress", "Update order fulfillment progress", "sales_orders"),
    ("sales_orders.hold", "Place sales orders on hold", "sales_orders"),
    ("sales_orders.cancel", "Cancel sales orders", "sales_orders"),
    ("sales_orders.amend", "Amend confirmed sales orders", "sales_orders"),
    ("sales_orders.manage_settings", "Manage sales order settings", "sales_orders"),
    ("invoices.view", "View invoices", "invoices"),
    ("invoices.create", "Create invoices", "invoices"),
    ("invoices.edit_draft", "Edit draft invoices", "invoices"),
    ("invoices.generate_from_order", "Generate invoices from sales orders", "invoices"),
    ("invoices.review", "Review and approve invoices", "invoices"),
    ("invoices.issue", "Issue finalized invoices", "invoices"),
    ("invoices.send", "Send invoices to clients", "invoices"),
    ("invoices.record_payment", "Record invoice payments", "invoices"),
    ("invoices.create_adjustment", "Create invoice adjustments and credit notes", "invoices"),
    ("invoices.cancel", "Cancel invoices", "invoices"),
    ("invoices.write_off", "Write off invoice balances", "invoices"),
    ("invoices.manage_settings", "Manage invoice settings", "invoices"),
    ("client_notes.view", "View client notes", "client_notes"),
    ("client_notes.create", "Create client notes", "client_notes"),
    ("client_notes.edit_own", "Edit own client notes", "client_notes"),
    ("client_notes.edit_all", "Edit all client notes", "client_notes"),
    ("client_notes.delete", "Delete client notes", "client_notes"),
    ("client_notes.pin", "Pin client notes", "client_notes"),
    ("client_notes.view_sensitive", "View sensitive client notes", "client_notes"),
    ("client_notes.manage_followups", "Manage client note follow-ups", "client_notes"),
    ("client_notes.manage_settings", "Manage client note settings", "client_notes"),
    ("reports.view", "View own sales reports", "reports"),
    ("reports.view_team", "View team sales reports", "reports"),
    ("reports.view_company", "View company-wide sales reports", "reports"),
    ("reports.view_financial", "View financial revenue reports", "reports"),
    ("reports.export", "Export sales reports", "reports"),
    ("reports.manage_saved_views", "Manage saved report views", "reports"),
    ("expenses.view", "View expenses", "expenses"),
    ("expenses.create", "Create expenses", "expenses"),
    ("expenses.edit_own", "Edit own expenses", "expenses"),
    ("expenses.edit_all", "Edit all expenses", "expenses"),
    ("expenses.submit", "Submit expenses for approval", "expenses"),
    ("expenses.approve", "Approve expenses", "expenses"),
    ("expenses.reject", "Reject expenses", "expenses"),
    ("expenses.mark_paid", "Mark expenses as paid", "expenses"),
    ("expenses.delete", "Delete draft expenses", "expenses"),
    ("expenses.export", "Export expenses", "expenses"),
    ("expenses.manage_settings", "Manage expense settings", "expenses"),
    ("purchase_orders.view", "View purchase orders", "purchase_orders"),
    ("purchase_orders.create", "Create purchase orders", "purchase_orders"),
    ("purchase_orders.edit_own", "Edit own purchase orders", "purchase_orders"),
    ("purchase_orders.edit_all", "Edit all purchase orders", "purchase_orders"),
    ("purchase_orders.submit", "Submit purchase orders for approval", "purchase_orders"),
    ("purchase_orders.approve", "Approve purchase orders", "purchase_orders"),
    ("purchase_orders.reject", "Reject purchase orders", "purchase_orders"),
    ("purchase_orders.send", "Send purchase orders to vendors", "purchase_orders"),
    ("purchase_orders.record_receipt", "Record purchase order receipts", "purchase_orders"),
    ("purchase_orders.record_billing", "Record purchase order billing", "purchase_orders"),
    ("purchase_orders.close", "Close purchase orders", "purchase_orders"),
    ("purchase_orders.delete", "Delete draft purchase orders", "purchase_orders"),
    ("purchase_orders.export", "Export purchase orders", "purchase_orders"),
    ("purchase_orders.manage_settings", "Manage purchase order settings", "purchase_orders"),
    ("inventory.view", "View inventory", "inventory"),
    ("inventory.enable_tracking", "Enable inventory tracking on products", "inventory"),
    ("inventory.record_opening", "Record opening stock", "inventory"),
    ("inventory.record_purchase", "Record purchase stock movements", "inventory"),
    ("inventory.record_sale", "Record sale stock movements", "inventory"),
    ("inventory.record_damage", "Record damage stock movements", "inventory"),
    ("inventory.adjust", "Record inventory adjustments", "inventory"),
    ("inventory.override_negative", "Override negative stock blocks", "inventory"),
    ("inventory.export", "Export inventory data", "inventory"),
    ("inventory.manage_settings", "Manage inventory settings", "inventory"),
    ("warehouses.view", "View warehouses and locations", "warehouses"),
    ("warehouses.manage_locations", "Manage warehouse locations", "warehouses"),
    ("warehouses.view_stock", "View stock by location", "warehouses"),
    ("warehouses.record_receipt", "Record warehouse receipts", "warehouses"),
    ("warehouses.record_issue", "Record warehouse issues", "warehouses"),
    ("warehouses.record_damage", "Record warehouse damage", "warehouses"),
    ("warehouses.adjust", "Record warehouse adjustments", "warehouses"),
    ("warehouses.transfer", "Transfer stock between locations", "warehouses"),
    ("warehouses.override_negative", "Override negative location stock blocks", "warehouses"),
    ("warehouses.export", "Export warehouse data", "warehouses"),
    ("warehouses.manage_settings", "Manage warehouse settings", "warehouses"),
    ("settings.view", "View system settings", "settings"),
    ("settings.edit", "Edit system settings", "settings"),
]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "Admin": [code for code, _, _ in PERMISSIONS],
    "Manager": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "contacts.view",
        "contacts.create",
        "contacts.edit",
        "products.view",
        "leads.view",
        "leads.create",
        "leads.edit",
        "leads.assign",
        "deals.view",
        "deals.create",
        "deals.edit",
        "deals.assign",
        "quotations.view",
        "quotations.create",
        "quotations.edit_draft",
        "quotations.submit_approval",
        "quotations.approve",
        "quotations.send",
        "quotations.cancel",
        "quotations.accept_override",
        "sales_orders.view",
        "sales_orders.create",
        "sales_orders.edit_draft",
        "sales_orders.convert_from_quote",
        "sales_orders.confirm",
        "sales_orders.update_progress",
        "sales_orders.hold",
        "sales_orders.cancel",
        "sales_orders.amend",
        "invoices.view",
        "invoices.create",
        "invoices.edit_draft",
        "invoices.generate_from_order",
        "invoices.review",
        "invoices.issue",
        "invoices.send",
        "invoices.record_payment",
        "invoices.create_adjustment",
        "invoices.cancel",
        "invoices.write_off",
        "client_notes.view",
        "client_notes.create",
        "client_notes.edit_own",
        "client_notes.edit_all",
        "client_notes.delete",
        "client_notes.pin",
        "client_notes.view_sensitive",
        "client_notes.manage_followups",
        "reports.view",
        "reports.view_team",
        "reports.view_company",
        "reports.view_financial",
        "reports.export",
        "expenses.view",
        "expenses.create",
        "expenses.edit_own",
        "expenses.edit_all",
        "expenses.submit",
        "expenses.approve",
        "expenses.reject",
        "expenses.mark_paid",
        "expenses.delete",
        "expenses.export",
        "purchase_orders.view",
        "purchase_orders.create",
        "purchase_orders.edit_own",
        "purchase_orders.edit_all",
        "purchase_orders.submit",
        "purchase_orders.approve",
        "purchase_orders.reject",
        "purchase_orders.send",
        "purchase_orders.record_receipt",
        "purchase_orders.record_billing",
        "purchase_orders.close",
        "purchase_orders.delete",
        "purchase_orders.export",
        "inventory.view",
        "inventory.enable_tracking",
        "inventory.record_opening",
        "inventory.record_purchase",
        "inventory.record_sale",
        "inventory.record_damage",
        "inventory.adjust",
        "inventory.override_negative",
        "inventory.export",
        "warehouses.view",
        "warehouses.manage_locations",
        "warehouses.view_stock",
        "warehouses.record_receipt",
        "warehouses.record_issue",
        "warehouses.record_damage",
        "warehouses.adjust",
        "warehouses.transfer",
        "warehouses.override_negative",
        "warehouses.export",
    ],
    "Employee": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "contacts.view",
        "products.view",
        "leads.view",
        "deals.view",
        "quotations.view",
        "quotations.create",
        "quotations.edit_draft",
        "quotations.submit_approval",
        "quotations.send",
        "sales_orders.view",
        "sales_orders.create",
        "sales_orders.edit_draft",
        "sales_orders.convert_from_quote",
        "sales_orders.confirm",
        "invoices.view",
        "invoices.create",
        "invoices.edit_draft",
        "invoices.generate_from_order",
        "client_notes.view",
        "client_notes.create",
        "client_notes.edit_own",
        "client_notes.pin",
        "client_notes.manage_followups",
        "reports.view",
        "expenses.view",
        "expenses.create",
        "expenses.edit_own",
        "expenses.submit",
        "purchase_orders.view",
        "purchase_orders.create",
        "purchase_orders.edit_own",
        "purchase_orders.submit",
        "purchase_orders.record_receipt",
        "inventory.view",
        "inventory.enable_tracking",
        "inventory.record_opening",
        "inventory.record_purchase",
        "inventory.record_sale",
        "inventory.record_damage",
        "warehouses.view",
        "warehouses.view_stock",
        "warehouses.record_receipt",
        "warehouses.record_issue",
        "warehouses.record_damage",
    ],
    "User": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
    ],
}
