"""Add numbering_configurations table

Revision ID: 58616cc45735
Revises: a7f2c8d41e09
Create Date: 2026-06-16 11:32:55.185609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58616cc45735'
down_revision: Union[str, Sequence[str], None] = 'a7f2c8d41e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbering_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('starting_number', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_numbering_configurations_entity_name'), 'numbering_configurations', ['entity_name'], unique=True)
    op.drop_index(op.f('ix_client_notes_contact_id'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_follow_up'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_note_type'), table_name='client_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_client_notes_note_type'), 'client_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_client_notes_follow_up'), 'client_notes', ['follow_up_required', 'follow_up_due_date'], unique=False)
    op.create_index(op.f('ix_client_notes_contact_id'), 'client_notes', ['contact_id'], unique=False)
    op.drop_index(op.f('ix_numbering_configurations_entity_name'), table_name='numbering_configurations')
    op.drop_table('numbering_configurations')
    # ### end Alembic commands ###
