"""create_uploaded_files_table

Revision ID: 71d74bce5773
Revises: h7i8j9k0l1m2
Create Date: 2026-06-16 21:05:46.192477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d74bce5773'
down_revision: Union[str, Sequence[str], None] = 'h7i8j9k0l1m2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('related_module', sa.String(length=50), nullable=True),
    sa.Column('related_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_related_module'), 'uploaded_files', ['related_module'], unique=False)
    op.create_index(op.f('ix_uploaded_files_related_record_id'), 'uploaded_files', ['related_record_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_stored_filename'), 'uploaded_files', ['stored_filename'], unique=True)
    op.drop_constraint(op.f('email_templates_name_key'), 'email_templates', type_='unique')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=False)
    op.create_unique_constraint(op.f('email_templates_name_key'), 'email_templates', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_uploaded_files_stored_filename'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_related_record_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_related_module'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
