from __future__ import annotations

"""add products table

Revision ID: a137febc890b
Revises: c0ee83e02ecc
Create Date: 2026-06-06 20:40:57.134853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a137febc890b'
down_revision: Union[str, Sequence[str], None] = 'c0ee83e02ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('service_code', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('sub_category', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('govt_charges', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('our_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('offer_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('filing_timeline', sa.String(length=80), nullable=True),
    sa.Column('completion_timeline', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_service_code'), 'products', ['service_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_service_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
